---

- name: Gather OS specific variables
  ansible.builtin.include_vars: "{{ loop_vars }}"
  loop: "{{ query('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family | lower }}-family.yml"
        - "{{ ansible_system | lower }}.yml"
      paths:
        - "vars"
      skip: true
  loop_control:
    loop_var: loop_vars

- name: Install redis in {{ ansible_distribution | lower }}
  ansible.builtin.include_tasks: "{{ loop_vars }}"
  loop: "{{ query('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family | lower }}-family.yml"
        - "{{ ansible_system | lower }}.yml"
      paths:
        - "tasks"
      skip: true
  loop_control:
    loop_var: loop_vars

- name: Create Redis Log directory
  ansible.builtin.file:
    path: "{{ redis_server_logdir }}"
    owner: redis
    group: redis
    # same mode than /var/log/redis/
    # created by the official redis-server package
    mode: 02750
    state: directory

- name: Create Redis Data directory
  ansible.builtin.file:
    path: "{{ redis_server_databases_dir }}"
    owner: redis
    group: redis
    mode: 0750
    state: directory

- name: "Include tasks for configure redis server"
  ansible.builtin.include_tasks: server.yml
  when: redis_server_enabled

# - import_tasks: sentinel.yml
#   when: redis_sentinel_enabled
