---
- name: Sentinel | Mask redis-sentinel service
  ansible.builtin.systemd:
    name: redis-sentinel.service
    masked: true

- name: Sentinel | Create Sentinel Log directory
  ansible.builtin.file:
    path: "{{ redis_sentinel_logdir }}"
    owner: redis
    group: redis
    # same mode than /var/log/redis/
    # created by the official redis-server package
    mode: 02750
    state: directory

- name: Sentinel | Create Sentinel Data directory
  ansible.builtin.file:
    path: "{{ redis_sentinel_databases_dir }}"
    owner: redis
    group: redis
    mode: 0750
    state: directory

- name: Sentinel | Create systemd unit file for redis
  ansible.builtin.template:
    src: etc/systemd/system/redis-sentinel@.service.j2
    dest: /etc/systemd/system/redis-sentinel@{{ redis_sentinel_port }}.service
    owner: root
    group: root
    mode: 0440
  register: _redis_sentinel_service

- name: Sentinel | Delete default sentinel configuration file
  ansible.builtin.file:
    path: /etc/redis/sentinel.conf
    state: absent

- name: Sentinel | Check config rewriten by SENTINEL
  ansible.builtin.lineinfile:
    path: /etc/redis/sentinel_{{ redis_sentinel_port }}.conf
    line: "# Generated by CONFIG REWRITE"
    state: absent
  check_mode: true
  changed_when: false
  register: _redis_sentinel_config_rewrite

- name: Sentinel | Configure redis-sentinel
  ansible.builtin.template:
    src: etc/redis/sentinel.conf.j2
    dest: /etc/redis/sentinel_{{ redis_sentinel_port }}.conf
    owner: redis
    group: redis
    mode: 0640
  notify: Redis-sentinel restart
  when: >-
    _redis_sentinel_config_rewrite.found is not defined
    or
    _redis_sentinel_config_rewrite.found != 1

- name: Sentinel | Activate redis-sentinel service
  ansible.builtin.systemd:
    name: redis-sentinel@{{ redis_sentinel_port }}.service
    masked: false
    state: started
    enabled: true
    daemon_reload: "{{ _redis_sentinel_service is changed }}"
