---
- name: sentinel | Mask redis-sentinel service
  systemd:
    name: redis-sentinel.service
    masked: true

- name: sentinel | Create Sentinel Log directory
  file:
    path: "{{ redis_sentinel_logdir }}"
    owner: redis
    group: redis
    # same mode than /var/log/redis/
    # created by the official redis-server package
    mode: 02750
    state: directory

- name: sentinel | Create Sentinel Data directory
  file:
    path: "{{ redis_sentinel_databases_dir }}"
    owner: redis
    group: redis
    mode: 0750
    state: directory

- name: sentinel | Create systemd unit file for redis
  template:
    src: etc/systemd/system/redis-sentinel@.service.j2
    dest: /etc/systemd/system/redis-sentinel@.service
    owner: root
    group: root
    mode: 0440
  register: redis_sentinel_service

- name: sentinel | Delete default sentinel configuration file
  file:
    path: /etc/redis/sentinel.conf
    state: absent

- name: sentinel | Check config rewriten by SENTINEL
  lineinfile:
    path: /etc/redis/sentinel_{{ redis_sentinel_port }}.conf
    line: "# Generated by CONFIG REWRITE"
    state: absent
  check_mode: true
  changed_when: false
  register: config_rewrite

- name: sentinel | Configure redis-sentinel
  template:
    src: etc/redis/sentinel.conf.j2
    dest: /etc/redis/sentinel_{{ redis_sentinel_port }}.conf
    owner: redis
    group: redis
    mode: 0640
  notify: redis-sentinel restart
  when: >-
    config_rewrite.found is not defined
    or
    config_rewrite.found == 0

- name: sentinel | Activate redis-sentinel service
  systemd:
    name: redis-sentinel@{{ redis_sentinel_port }}.service
    masked: false
    enabled: true
    daemon_reload: "{{ redis_sentinel_service is changed }}"

- name: sentinel | Check service sentinel is started
  systemd:
    name: redis-sentinel@{{ redis_sentinel_port }}.service
    state: started
