---
dependency:
  name: shell
  command: python3 -m pip install pytest-testinfra && ansible-galaxy collection install community.general

driver:
  name: docker

platforms:
  # On "${name:-${image:-debian}", the last brace does not miss, it works like that...
  # The env var should be used when the image variable refers to a full registry path like registry.access.redhat.com/ubi8/ubi
  - &instance
    name: claranet_redis_${name:-${image:-debian}-${tag:-latest}-${scenario:-master-slave}_master
    image: ${image:-debian}:${tag:-latest}
    privileged: true
    tty: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    stop_signal: "SIGRTMIN+3"
    capabilities:
      - SYS_ADMIN
      - SYS_TIME
      - LINUX_IMMUTABLE
    command: "/lib/systemd/systemd"
    groups:
      - redis

  - <<: *instance
    name: claranet_redis_${name:-${image:-debian}-${tag:-latest}-${scenario:-master-slave}_replica1

  - <<: *instance
    name: claranet_redis_${name:-${image:-debian}-${tag:-latest}-${scenario:-master-slave}_replica2


provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
  options:
    v: true
  inventory:
    host_vars:
      claranet_redis_${name:-${image:-debian}-${tag:-latest}-${scenario:-master-slave}_master:
        redis_role: master
        test: master1
      claranet_redis_${name:-${image:-debian}-${tag:-latest}-${scenario:-master-slave}_replica1:
        redis_role: replica
        test: replica1
      claranet_redis_${name:-${image:-debian}-${tag:-latest}-${scenario:-master-slave}_replica2:
        redis_role: replica
        name: replica2

verifier:
  name: testinfra
  options:
    verbose: true
    s: true

lint: |
  set -e
  yamllint .
  ansible-lint
