---
- name: Redis-server restart
  ansible.builtin.debug:
    msg:
      - "****"
      - "**** !!! MANUAL RESTART NEEDED !!!"
      - "**** Configuration files changed, you have to restart redis manually"
      - "****"
  when:
    - systemctl_start_redis_server is defined
    - systemctl_start_redis_server is not changed

- name: Redis-sentinel restart
  ansible.builtin.systemd:
    name: "redis-sentinel@{{ redis_sentinel_port }}.service"
    state: restarted
